---
title: "April data collection first round"
author: "Benny deMayo"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(png)
library(knitr)
library(markdown)
library(lmerTest)
library(ggthemes)
library(psych)
library(magrittr)
library(langcog)
library(tidyboot)
library(fs)
library(zipcode)
library(ggmap)
library(lubridate)

source(path(here::here(), "file_paths.R"))
```


```{r}
readInWebCdiSummary <- function(summary_df) {
  clean_data <- 
    read_csv(summary_df, col_types = cols(.default = col_character())) %>% 
    mutate_at(
      .funs = ~case_when(
        str_detect(., "<") ~ 1, #get rid of entries that have 'less than' signs in them
        TRUE ~ as.numeric(.)
      ),
      .vars = vars(contains("Percentile"))
    ) %>% 
    mutate_at(
      .funs = ~as.numeric(.), #turn all the quantitative columns back into numeric
      .vars = 
       vars(
          which(colnames(.) == "benchmark age"):ncol(.)
        )
    )
}

round_4_raw <- 
  readInWebCdiSummary(ses_round_4) %>% 
  filter(completed == TRUE)
```


```{r}
filterBirthweight <- function(data) {
  clean_data <- 
    data %>% 
    mutate_at(
      .vars = c("due_date_diff", "birth_weight_lb"),
      .funs = ~as.numeric(.)
    ) %>% 
    mutate_at(
      .vars = c("due_date_diff"),
      .funs = ~case_when(
        is.na(.) ~ 0, #turn non-NA's in this column into zeros
        TRUE ~ .
      )
    ) %>% 
    mutate(premature = due_date_diff >= 4 & birth_weight_lb < 5.5) %>% 
    filter(premature == FALSE)
  
  return(clean_data)
}

filterMultilingual <- function(data) {
  clean_data <- 
    data %>% 
    mutate_at(
      .vars = c("language_days_per_week", "language_hours_per_day"),
      .funs = ~as.numeric(.)
    ) %>% 
    mutate(
      language_hours_per_week = language_days_per_week * language_hours_per_day
    ) %>% 
    filter(is.na(language_hours_per_week) | language_hours_per_week <= 16)
}

filterVision <- function(data) {
  clean_data <- 
    data %>% 
    filter(
      hearing_loss_boolean != "1" | is.na(hearing_loss_boolean),
      vision_problems_boolean != "1" | is.na(vision_problems_boolean)
    )
  
  return(clean_data)
}

getCompletionInterval <- function(data) {
  clean_data <- 
    data %>% 
    mutate(
      completion_interval = lubridate::interval(created_date, last_modified),
      completion_time = completion_interval / lubridate::minutes()
    )
  
  return(clean_data)
}

```


```{r}
round_4_filtered <- 
  round_4_raw %>% 
  filterBirthweight() %>% 
  filterMultilingual() %>% 
  filterVision() %>% 
  getCompletionInterval()

round_4_filtered %>% 
  ggplot(aes(completion_time)) +
  geom_histogram()

round_4_filtered %>% 
  ggplot(aes(completion_time, age)) +
  geom_point()

round_4_filtered %>% 
  ggplot(aes(mother_yob)) +
  geom_histogram(stat = "count")

```


```{r}
getEthnicities <- function(data) {
  clean_data <- 
    data %>% 
    mutate( #get rid of brackets in ethnicity column
      child_ethnicity = str_replace_all(child_ethnicity, "[^[:upper:]]", "")
    ) %>% 
    mutate(
      ethnicity_white = str_detect(child_ethnicity, "W"),
      ethnicity_black = str_detect(child_ethnicity, "B"),
      ethnicity_asian = str_detect(child_ethnicity, "A"),
      ethnicity_native = str_detect(child_ethnicity, "N"),
      ethnicity_other = str_detect(child_ethnicity, "O"),
      ethnicity_mixed = str_length(child_ethnicity) > 1
    )

  old_ethnicity_numbers <- 
   tibble(
      ethnicity = c("Asian", "Black", "Mixed", "White"),
      `2007 manual` = c(.069, .105, .063, .733)
    )
  
  clean_data <- 
    clean_data %>% 
    mutate( #get rid of brackets in ethnicity column
      child_ethnicity = str_replace_all(child_ethnicity, "[^[:upper:]]", "")
    ) %>%
    mutate(
      ethnicity = case_when(
        str_length(child_ethnicity) > 1 ~ "mixed",
        TRUE ~ child_ethnicity
      ) %>% fct_recode(
        Asian = "A",
        Black = "B",
        Mixed = "mixed",
        White = "W"
      )
    ) %>% 
    filter(ethnicity != "") %>% 
    select(subject_id, child_ethnicity, ethnicity) %>% 
    count(ethnicity) %>% 
    mutate(`Current study` = n / sum(n)) %>% 
    left_join(
      old_ethnicity_numbers,
      by = c("ethnicity")
    ) %>% 
    pivot_longer(
      cols = c(`Current study`, `2007 manual`),
      names_to = "study",
      values_to = "proportion"
    )
  
  return(clean_data)
}
```


```{r}
round_4_eth <- 
  round_4_filtered %>% 
  getEthnicities()
```

